# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e174855b64ae2edd83d7e8ed2bdfa1a4f7a2408419837ac80f1ed6867917b1d27e2b4cd9a15dba5499697ee6746b491533b6ce114a46e52f5b420a5db3bf6f3a

test:
  secret_key_base: b2009ad22a48568f7a085a0e7b56943a48bf6cf5f4c7f967b771b2e0cd6cd5e21cea8b32b8cc60513094050b346b14e8d526080638908dcd4e890d0ea31c8023

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
